spring:
  application:
    name: gerenciamento-pets
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        default_schema: gerenciamento_pets
        format_sql: true
  datasource:
    url: jdbc:h2:file:./src/main/resources/db/pets;INIT=CREATE SCHEMA IF NOT EXISTS gerenciamento_pets;DB_CLOSE_DELAY=-1
    username: ${USERNAME_DATABASE:sa}
    password: ${PASSWORD_DATABASE:}
  sql:
    init:
      mode: always